library(targets)
library(tarchetypes)
library(quarto)
library(here)


# General pipeline settings ----

suppressPackageStartupMessages(library(brms))

# Taken from Andrew Heiss (https://github.com/andrewheiss/cautioning-canary/blob/master/_targets.R)

#   - If using cmdstanr, you can use within-chain threading
#   - (https://cran.r-project.org/web/packages/brms/vignettes/brms_threading.html)
#   - On a four-core computer, use mc.cores = 2 and threads = threading(2)
#   - On an eight+-core computer, use mc.cores = 4 and threads = threading(2)
options(
  mc.cores = 3,
  mc.threads = 2,
  brms.backend = "cmdstanr"
)

options(
  tidyverse.quiet = TRUE,
  dplyr.summarise.inform = FALSE
)

# R functions ----

source("R/packages.R")
source("R/data_cleaning.R")
source("R/dags.R")
source("R/aggressive_care_prior_models.R")
source("R/aggressive_care_posterior_models.R")
source("R/diagnostics.R")
# source("R/results_visualization.R")
source("R/outcomes_prior_models.R")
source("R/outcomes_posterior_models.R")
# source("R/results_outcomes.R")
source("R/predictive_checks.R")
source("R/posterior_diagnostics.R")
source("R/table1.R")
source("R/table2.R")
source("R/table3.R")
source("R/figures.R")


# Pipeline ----
tar_plan(

  ## Define raw data file ----
  tar_file_read(
    imported_data,
    "data/raw_data/all.rds",
    read_rds(!!.x)
  ),

  ## Select, filter, and clean data ----
  selected_data = select_variables(imported_data),
  ich_all = filter_variables(selected_data),
  ich_aggressive = ich_all |> filter(study == "ERICH" | study == "ATACH-2") |> droplevels(),
  erich = ich_all |> filter(study == "ERICH") |> droplevels(),
  atach = ich_all |> filter(study == "ATACH-2") |> droplevels(),

  ## DAGs ----
  dag_aggressive = aggressive_dag_function(x),
  dag_outcomes = outcomes_dag_function(x),

  ## Aggressive Care ----

  ### Priors ----
  settings = model_setup(),
  m_prior_neutral_neurosurgery = f_prior_neutral_neurosurgery(ich_aggressive),
  m_prior_left_neurosurgery = f_prior_left_neurosurgery(ich_aggressive),
  m_prior_right_neurosurgery = f_prior_right_neurosurgery(ich_aggressive),
  m_prior_flat_neurosurgery = f_prior_flat_neurosurgery(ich_aggressive),
  m_prior_neutral_evd = f_prior_neutral_evd(ich_aggressive),
  m_prior_left_evd = f_prior_left_evd(ich_aggressive),
  m_prior_right_evd = f_prior_right_evd(ich_aggressive),
  m_prior_flat_evd = f_prior_flat_evd(ich_aggressive),
  m_prior_neutral_tracheostomy = f_prior_neutral_tracheostomy(ich_aggressive),
  m_prior_left_tracheostomy = f_prior_left_tracheostomy(ich_aggressive),
  m_prior_right_tracheostomy = f_prior_right_tracheostomy(ich_aggressive),
  m_prior_flat_tracheostomy = f_prior_flat_tracheostomy(ich_aggressive),
  m_prior_neutral_days_mechanical_ventilation = f_prior_neutral_days_mechanical_ventilation(ich_aggressive),
  m_prior_left_days_mechanical_ventilation = f_prior_left_days_mechanical_ventilation(ich_aggressive),
  m_prior_right_days_mechanical_ventilation = f_prior_right_days_mechanical_ventilation(ich_aggressive),
  m_prior_flat_days_mechanical_ventilation = f_prior_flat_days_mechanical_ventilation(ich_aggressive),
  m_prior_neutral_comfort = f_prior_neutral_comfort(ich_aggressive),
  m_prior_left_comfort = f_prior_left_comfort(ich_aggressive),
  m_prior_right_comfort = f_prior_right_comfort(ich_aggressive),
  m_prior_flat_comfort = f_prior_flat_comfort(ich_aggressive),
  m_prior_neutral_early_wlst = f_prior_neutral_early_wlst(ich_aggressive),
  m_prior_left_early_wlst = f_prior_left_early_wlst(ich_aggressive),
  m_prior_right_early_wlst = f_prior_right_early_wlst(ich_aggressive),
  m_prior_flat_early_wlst = f_prior_flat_early_wlst(ich_aggressive),
  m_prior_neutral_dnr_binary = f_prior_neutral_dnr_binary(ich_aggressive),
  m_prior_left_dnr_binary = f_prior_left_dnr_binary(ich_aggressive),
  m_prior_right_dnr_binary = f_prior_right_dnr_binary(ich_aggressive),
  m_prior_flat_dnr_binary = f_prior_flat_dnr_binary(ich_aggressive),

  ### Prior Predictive Checks ----
  prior_check_neurosurgery = f_prior_predictive_check(m_prior_neutral_neurosurgery, m_prior_left_neurosurgery, m_prior_right_neurosurgery, m_prior_flat_neurosurgery),
  prior_visual_neurosurgery_neutral = prediction_visual(m_prior_neutral_neurosurgery),
  prior_visual_neurosurgery_left = prediction_visual(m_prior_left_neurosurgery),
  prior_visual_neurosurgery_right = prediction_visual(m_prior_right_neurosurgery),
  prior_visual_neurosurgery_flat = prediction_visual(m_prior_flat_neurosurgery),
  prior_check_evd = f_prior_predictive_check(m_prior_neutral_evd, m_prior_left_evd, m_prior_right_evd, m_prior_flat_evd),
  prior_visual_evd_neutral = prediction_visual(m_prior_neutral_evd),
  prior_visual_evd_left = prediction_visual(m_prior_left_evd),
  prior_visual_evd_right = prediction_visual(m_prior_right_evd),
  prior_visual_evd_flat = prediction_visual(m_prior_flat_evd),
  prior_check_tracheostomy = f_prior_predictive_check(m_prior_neutral_tracheostomy, m_prior_left_tracheostomy, m_prior_right_tracheostomy, m_prior_flat_tracheostomy),
  prior_visual_tracheostomy_neutral = prediction_visual(m_prior_neutral_tracheostomy),
  prior_visual_tracheostomy_left = prediction_visual(m_prior_left_tracheostomy),
  prior_visual_tracheostomy_right = prediction_visual(m_prior_right_tracheostomy),
  prior_visual_tracheostomy_flat = prediction_visual(m_prior_flat_tracheostomy),
  prior_check_days_mechanical_ventilation = f_prior_predictive_check(m_prior_neutral_days_mechanical_ventilation, m_prior_left_days_mechanical_ventilation, m_prior_right_days_mechanical_ventilation, m_prior_flat_days_mechanical_ventilation),
  prior_visual_days_mechanical_ventilation_neutral = prediction_visual(m_prior_neutral_days_mechanical_ventilation),
  prior_visual_days_mechanical_ventilation_left = prediction_visual(m_prior_left_days_mechanical_ventilation),
  prior_visual_days_mechanical_ventilation_right = prediction_visual(m_prior_right_days_mechanical_ventilation),
  prior_visual_days_mechanical_ventilation_flat = prediction_visual(m_prior_flat_days_mechanical_ventilation),
  prior_check_comfort = f_prior_predictive_check(m_prior_neutral_comfort, m_prior_left_comfort, m_prior_right_comfort, m_prior_flat_comfort),
  prior_visual_comfort_neutral = prediction_visual(m_prior_neutral_comfort),
  prior_visual_comfort_left = prediction_visual(m_prior_left_comfort),
  prior_visual_comfort_right = prediction_visual(m_prior_right_comfort),
  prior_visual_comfort_flat = prediction_visual(m_prior_flat_comfort),
  prior_check_early_wlst = f_prior_predictive_check(m_prior_neutral_early_wlst, m_prior_left_early_wlst, m_prior_right_early_wlst, m_prior_flat_early_wlst),
  prior_visual_early_wlst_neutral = prediction_visual(m_prior_neutral_early_wlst),
  prior_visual_early_wlst_left = prediction_visual(m_prior_left_early_wlst),
  prior_visual_early_wlst_right = prediction_visual(m_prior_right_early_wlst),
  prior_visual_early_wlst_flat = prediction_visual(m_prior_flat_early_wlst),
  prior_check_dnr_binary = f_prior_predictive_check(m_prior_neutral_dnr_binary, m_prior_left_dnr_binary, m_prior_right_dnr_binary, m_prior_flat_dnr_binary),
  prior_visual_dnr_binary_neutral = prediction_visual(m_prior_neutral_dnr_binary),
  prior_visual_dnr_binary_left = prediction_visual(m_prior_left_dnr_binary),
  prior_visual_dnr_binary_right = prediction_visual(m_prior_right_dnr_binary),
  prior_visual_dnr_binary_flat = prediction_visual(m_prior_flat_dnr_binary),

  ### Posterior Simulation ----
  m_posterior_neutral_neurosurgery = f_posterior_neutral_neurosurgery(ich_aggressive),
  m_posterior_left_neurosurgery = f_posterior_left_neurosurgery(ich_aggressive),
  m_posterior_right_neurosurgery = f_posterior_right_neurosurgery(ich_aggressive),
  m_posterior_flat_neurosurgery = f_posterior_flat_neurosurgery(ich_aggressive),
  m_posterior_neutral_evd = f_posterior_neutral_evd(ich_aggressive),
  m_posterior_left_evd = f_posterior_left_evd(ich_aggressive),
  m_posterior_right_evd = f_posterior_right_evd(ich_aggressive),
  m_posterior_flat_evd = f_posterior_flat_evd(ich_aggressive),
  m_posterior_neutral_tracheostomy = f_posterior_neutral_tracheostomy(ich_aggressive),
  m_posterior_left_tracheostomy = f_posterior_left_tracheostomy(ich_aggressive),
  m_posterior_right_tracheostomy = f_posterior_right_tracheostomy(ich_aggressive),
  m_posterior_flat_tracheostomy = f_posterior_flat_tracheostomy(ich_aggressive),
  m_posterior_neutral_days_mechanical_ventilation = f_posterior_neutral_days_mechanical_ventilation(ich_aggressive),
  m_posterior_left_days_mechanical_ventilation = f_posterior_left_days_mechanical_ventilation(ich_aggressive),
  m_posterior_right_days_mechanical_ventilation = f_posterior_right_days_mechanical_ventilation(ich_aggressive),
  m_posterior_flat_days_mechanical_ventilation = f_posterior_flat_days_mechanical_ventilation(ich_aggressive),
  m_posterior_neutral_comfort = f_posterior_neutral_comfort(ich_aggressive),
  m_posterior_left_comfort = f_posterior_left_comfort(ich_aggressive),
  m_posterior_right_comfort = f_posterior_right_comfort(ich_aggressive),
  m_posterior_flat_comfort = f_posterior_flat_comfort(ich_aggressive),
  m_posterior_neutral_early_wlst = f_posterior_neutral_early_wlst(ich_aggressive),
  m_posterior_left_early_wlst = f_posterior_left_early_wlst(ich_aggressive),
  m_posterior_right_early_wlst = f_posterior_right_early_wlst(ich_aggressive),
  m_posterior_flat_early_wlst = f_posterior_flat_early_wlst(ich_aggressive),
  m_posterior_neutral_dnr_binary = f_posterior_neutral_dnr_binary(ich_aggressive),
  m_posterior_left_dnr_binary = f_posterior_left_dnr_binary(ich_aggressive),
  m_posterior_right_dnr_binary = f_posterior_right_dnr_binary(ich_aggressive),
  m_posterior_flat_dnr_binary = f_posterior_flat_dnr_binary(ich_aggressive),

  ## Outcomes ----

  ### Priors ----
  m_prior_mrs_90_minimal = f_prior_mrs_90_minimal(ich_aggressive),
  m_prior_neutral_mrs_90_canonical = f_prior_neutral_mrs_90_canonical(ich_aggressive),
  m_prior_left_mrs_90_canonical = f_prior_left_mrs_90_canonical(ich_aggressive),
  m_prior_right_mrs_90_canonical = f_prior_right_mrs_90_canonical(ich_aggressive),
  m_prior_flat_mrs_90_canonical = f_prior_flat_mrs_90_canonical(ich_aggressive),
  m_prior_mrs_180_minimal = f_prior_mrs_180_minimal(ich_aggressive),
  m_prior_neutral_mrs_180_canonical = f_prior_neutral_mrs_180_canonical(ich_aggressive),
  m_prior_left_mrs_180_canonical = f_prior_left_mrs_180_canonical(ich_aggressive),
  m_prior_right_mrs_180_canonical = f_prior_right_mrs_180_canonical(ich_aggressive),
  m_prior_flat_mrs_180_canonical = f_prior_flat_mrs_180_canonical(ich_aggressive),
  m_prior_mrs_365_minimal = f_prior_mrs_365_minimal(ich_aggressive),
  m_prior_neutral_mrs_365_canonical = f_prior_neutral_mrs_365_canonical(ich_aggressive),
  m_prior_left_mrs_365_canonical = f_prior_left_mrs_365_canonical(ich_aggressive),
  m_prior_right_mrs_365_canonical = f_prior_right_mrs_365_canonical(ich_aggressive),
  m_prior_flat_mrs_365_canonical = f_prior_flat_mrs_365_canonical(ich_aggressive),
  m_prior_neutral_euro_mobility_90_canonical = f_prior_neutral_euro_mobility_90_canonical(ich_aggressive),
  m_prior_left_euro_mobility_90_canonical = f_prior_left_euro_mobility_90_canonical(ich_aggressive),
  m_prior_right_euro_mobility_90_canonical = f_prior_right_euro_mobility_90_canonical(ich_aggressive),
  m_prior_flat_euro_mobility_90_canonical = f_prior_flat_euro_mobility_90_canonical(ich_aggressive),
  m_prior_neutral_euro_mobility_180_canonical = f_prior_neutral_euro_mobility_180_canonical(ich_aggressive),
  m_prior_left_euro_mobility_180_canonical = f_prior_left_euro_mobility_180_canonical(ich_aggressive),
  m_prior_right_euro_mobility_180_canonical = f_prior_right_euro_mobility_180_canonical(ich_aggressive),
  m_prior_flat_euro_mobility_180_canonical = f_prior_flat_euro_mobility_180_canonical(ich_aggressive),
  m_prior_neutral_euro_mobility_365_canonical = f_prior_neutral_euro_mobility_365_canonical(ich_aggressive),
  m_prior_left_euro_mobility_365_canonical = f_prior_left_euro_mobility_365_canonical(ich_aggressive),
  m_prior_right_euro_mobility_365_canonical = f_prior_right_euro_mobility_365_canonical(ich_aggressive),
  m_prior_flat_euro_mobility_365_canonical = f_prior_flat_euro_mobility_365_canonical(ich_aggressive),
  m_prior_neutral_euro_selfcare_90_canonical = f_prior_neutral_euro_selfcare_90_canonical(ich_aggressive),
  m_prior_left_euro_selfcare_90_canonical = f_prior_left_euro_selfcare_90_canonical(ich_aggressive),
  m_prior_right_euro_selfcare_90_canonical = f_prior_right_euro_selfcare_90_canonical(ich_aggressive),
  m_prior_flat_euro_selfcare_90_canonical = f_prior_flat_euro_selfcare_90_canonical(ich_aggressive),
  m_prior_neutral_euro_selfcare_180_canonical = f_prior_neutral_euro_selfcare_180_canonical(ich_aggressive),
  m_prior_left_euro_selfcare_180_canonical = f_prior_left_euro_selfcare_180_canonical(ich_aggressive),
  m_prior_right_euro_selfcare_180_canonical = f_prior_right_euro_selfcare_180_canonical(ich_aggressive),
  m_prior_flat_euro_selfcare_180_canonical = f_prior_flat_euro_selfcare_180_canonical(ich_aggressive),
  m_prior_neutral_euro_selfcare_365_canonical = f_prior_neutral_euro_selfcare_365_canonical(ich_aggressive),
  m_prior_left_euro_selfcare_365_canonical = f_prior_left_euro_selfcare_365_canonical(ich_aggressive),
  m_prior_right_euro_selfcare_365_canonical = f_prior_right_euro_selfcare_365_canonical(ich_aggressive),
  m_prior_flat_euro_selfcare_365_canonical = f_prior_flat_euro_selfcare_365_canonical(ich_aggressive),
  m_prior_neutral_euro_usual_90_canonical = f_prior_neutral_euro_usual_90_canonical(ich_aggressive),
  m_prior_left_euro_usual_90_canonical = f_prior_left_euro_usual_90_canonical(ich_aggressive),
  m_prior_right_euro_usual_90_canonical = f_prior_right_euro_usual_90_canonical(ich_aggressive),
  m_prior_flat_euro_usual_90_canonical = f_prior_flat_euro_usual_90_canonical(ich_aggressive),
  m_prior_neutral_euro_usual_180_canonical = f_prior_neutral_euro_usual_180_canonical(ich_aggressive),
  m_prior_left_euro_usual_180_canonical = f_prior_left_euro_usual_180_canonical(ich_aggressive),
  m_prior_right_euro_usual_180_canonical = f_prior_right_euro_usual_180_canonical(ich_aggressive),
  m_prior_flat_euro_usual_180_canonical = f_prior_flat_euro_usual_180_canonical(ich_aggressive),
  m_prior_neutral_euro_usual_365_canonical = f_prior_neutral_euro_usual_365_canonical(ich_aggressive),
  m_prior_left_euro_usual_365_canonical = f_prior_left_euro_usual_365_canonical(ich_aggressive),
  m_prior_right_euro_usual_365_canonical = f_prior_right_euro_usual_365_canonical(ich_aggressive),
  m_prior_flat_euro_usual_365_canonical = f_prior_flat_euro_usual_365_canonical(ich_aggressive),
  m_prior_neutral_euro_pain_90_canonical = f_prior_neutral_euro_pain_90_canonical(ich_aggressive),
  m_prior_left_euro_pain_90_canonical = f_prior_left_euro_pain_90_canonical(ich_aggressive),
  m_prior_right_euro_pain_90_canonical = f_prior_right_euro_pain_90_canonical(ich_aggressive),
  m_prior_flat_euro_pain_90_canonical = f_prior_flat_euro_pain_90_canonical(ich_aggressive),
  m_prior_neutral_euro_pain_180_canonical = f_prior_neutral_euro_pain_180_canonical(ich_aggressive),
  m_prior_left_euro_pain_180_canonical = f_prior_left_euro_pain_180_canonical(ich_aggressive),
  m_prior_right_euro_pain_180_canonical = f_prior_right_euro_pain_180_canonical(ich_aggressive),
  m_prior_flat_euro_pain_180_canonical = f_prior_flat_euro_pain_180_canonical(ich_aggressive),
  m_prior_neutral_euro_pain_365_canonical = f_prior_neutral_euro_pain_365_canonical(ich_aggressive),
  m_prior_left_euro_pain_365_canonical = f_prior_left_euro_pain_365_canonical(ich_aggressive),
  m_prior_right_euro_pain_365_canonical = f_prior_right_euro_pain_365_canonical(ich_aggressive),
  m_prior_flat_euro_pain_365_canonical = f_prior_flat_euro_pain_365_canonical(ich_aggressive),
  m_prior_neutral_euro_anxiety_90_canonical = f_prior_neutral_euro_anxiety_90_canonical(ich_aggressive),
  m_prior_left_euro_anxiety_90_canonical = f_prior_left_euro_anxiety_90_canonical(ich_aggressive),
  m_prior_right_euro_anxiety_90_canonical = f_prior_right_euro_anxiety_90_canonical(ich_aggressive),
  m_prior_flat_euro_anxiety_90_canonical = f_prior_flat_euro_anxiety_90_canonical(ich_aggressive),
  m_prior_neutral_euro_anxiety_180_canonical = f_prior_neutral_euro_anxiety_180_canonical(ich_aggressive),
  m_prior_left_euro_anxiety_180_canonical = f_prior_left_euro_anxiety_180_canonical(ich_aggressive),
  m_prior_right_euro_anxiety_180_canonical = f_prior_right_euro_anxiety_180_canonical(ich_aggressive),
  m_prior_flat_euro_anxiety_180_canonical = f_prior_flat_euro_anxiety_180_canonical(ich_aggressive),
  m_prior_neutral_euro_anxiety_365_canonical = f_prior_neutral_euro_anxiety_365_canonical(ich_aggressive),
  m_prior_left_euro_anxiety_365_canonical = f_prior_left_euro_anxiety_365_canonical(ich_aggressive),
  m_prior_right_euro_anxiety_365_canonical = f_prior_right_euro_anxiety_365_canonical(ich_aggressive),
  m_prior_flat_euro_anxiety_365_canonical = f_prior_flat_euro_anxiety_365_canonical(ich_aggressive),

  ### Prior Predictive Checks ----
  prior_check_mrs_90 = f_prior_predictive_check(m_prior_neutral_mrs_90_canonical, m_prior_left_mrs_90_canonical, m_prior_right_mrs_90_canonical, m_prior_flat_mrs_90_canonical),
  prior_visual_mrs_90_neutral = prediction_visual(m_prior_neutral_mrs_90_canonical),
  prior_visual_mrs_90_left = prediction_visual(m_prior_left_mrs_90_canonical),
  prior_visual_mrs_90_right = prediction_visual(m_prior_right_mrs_90_canonical),
  prior_visual_mrs_90_flat = prediction_visual(m_prior_flat_mrs_90_canonical),
  prior_check_mrs_180 = f_prior_predictive_check(m_prior_neutral_mrs_180_canonical, m_prior_left_mrs_180_canonical, m_prior_right_mrs_180_canonical, m_prior_flat_mrs_180_canonical),
  prior_visual_mrs_180_neutral = prediction_visual(m_prior_neutral_mrs_180_canonical),
  prior_visual_mrs_180_left = prediction_visual(m_prior_left_mrs_180_canonical),
  prior_visual_mrs_180_right = prediction_visual(m_prior_right_mrs_180_canonical),
  prior_visual_mrs_180_flat = prediction_visual(m_prior_flat_mrs_180_canonical),
  prior_check_mrs_365 = f_prior_predictive_check(m_prior_neutral_mrs_365_canonical, m_prior_left_mrs_365_canonical, m_prior_right_mrs_365_canonical, m_prior_flat_mrs_365_canonical),
  prior_visual_mrs_365_neutral = prediction_visual(m_prior_neutral_mrs_365_canonical),
  prior_visual_mrs_365_left = prediction_visual(m_prior_left_mrs_365_canonical),
  prior_visual_mrs_365_right = prediction_visual(m_prior_right_mrs_365_canonical),
  prior_visual_mrs_365_flat = prediction_visual(m_prior_flat_mrs_365_canonical),
  prior_check_euro_mobility_90 = f_prior_predictive_check(m_prior_neutral_euro_mobility_90_canonical, m_prior_left_euro_mobility_90_canonical, m_prior_right_euro_mobility_90_canonical, m_prior_flat_euro_mobility_90_canonical),
  prior_visual_euro_mobility_90_neutral = prediction_visual(m_prior_neutral_euro_mobility_90_canonical),
  prior_visual_euro_mobility_90_left = prediction_visual(m_prior_left_euro_mobility_90_canonical),
  prior_visual_euro_mobility_90_right = prediction_visual(m_prior_right_euro_mobility_90_canonical),
  prior_visual_euro_mobility_90_flat = prediction_visual(m_prior_flat_euro_mobility_90_canonical),
  prior_check_euro_mobility_180 = f_prior_predictive_check(m_prior_neutral_euro_mobility_180_canonical, m_prior_left_euro_mobility_180_canonical, m_prior_right_euro_mobility_180_canonical, m_prior_flat_euro_mobility_180_canonical),
  prior_visual_euro_mobility_180_neutral = prediction_visual(m_prior_neutral_euro_mobility_180_canonical),
  prior_visual_euro_mobility_180_left = prediction_visual(m_prior_left_euro_mobility_180_canonical),
  prior_visual_euro_mobility_180_right = prediction_visual(m_prior_right_euro_mobility_180_canonical),
  prior_visual_euro_mobility_180_flat = prediction_visual(m_prior_flat_euro_mobility_180_canonical),
  prior_check_euro_mobility_365 = f_prior_predictive_check(m_prior_neutral_euro_mobility_365_canonical, m_prior_left_euro_mobility_365_canonical, m_prior_right_euro_mobility_365_canonical, m_prior_flat_euro_mobility_365_canonical),
  prior_visual_euro_mobility_365_neutral = prediction_visual(m_prior_neutral_euro_mobility_365_canonical),
  prior_visual_euro_mobility_365_left = prediction_visual(m_prior_left_euro_mobility_365_canonical),
  prior_visual_euro_mobility_365_right = prediction_visual(m_prior_right_euro_mobility_365_canonical),
  prior_visual_euro_mobility_365_flat = prediction_visual(m_prior_flat_euro_mobility_365_canonical),
  prior_check_euro_usual_90 = f_prior_predictive_check(m_prior_neutral_euro_usual_90_canonical, m_prior_left_euro_usual_90_canonical, m_prior_right_euro_usual_90_canonical, m_prior_flat_euro_usual_90_canonical),
  prior_visual_euro_usual_90_neutral = prediction_visual(m_prior_neutral_euro_usual_90_canonical),
  prior_visual_euro_usual_90_left = prediction_visual(m_prior_left_euro_usual_90_canonical),
  prior_visual_euro_usual_90_right = prediction_visual(m_prior_right_euro_usual_90_canonical),
  prior_visual_euro_usual_90_flat = prediction_visual(m_prior_flat_euro_usual_90_canonical),
  prior_check_euro_usual_180 = f_prior_predictive_check(m_prior_neutral_euro_usual_180_canonical, m_prior_left_euro_usual_180_canonical, m_prior_right_euro_usual_180_canonical, m_prior_flat_euro_usual_180_canonical),
  prior_visual_euro_usual_180_neutral = prediction_visual(m_prior_neutral_euro_usual_180_canonical),
  prior_visual_euro_usual_180_left = prediction_visual(m_prior_left_euro_usual_180_canonical),
  prior_visual_euro_usual_180_right = prediction_visual(m_prior_right_euro_usual_180_canonical),
  prior_visual_euro_usual_180_flat = prediction_visual(m_prior_flat_euro_usual_180_canonical),
  prior_check_euro_usual_365 = f_prior_predictive_check(m_prior_neutral_euro_usual_365_canonical, m_prior_left_euro_usual_365_canonical, m_prior_right_euro_usual_365_canonical, m_prior_flat_euro_usual_365_canonical),
  prior_visual_euro_usual_365_neutral = prediction_visual(m_prior_neutral_euro_usual_365_canonical),
  prior_visual_euro_usual_365_left = prediction_visual(m_prior_left_euro_usual_365_canonical),
  prior_visual_euro_usual_365_right = prediction_visual(m_prior_right_euro_usual_365_canonical),
  prior_visual_euro_usual_365_flat = prediction_visual(m_prior_flat_euro_usual_365_canonical),
  prior_check_euro_selfcare_90 = f_prior_predictive_check(m_prior_neutral_euro_selfcare_90_canonical, m_prior_left_euro_selfcare_90_canonical, m_prior_right_euro_selfcare_90_canonical, m_prior_flat_euro_selfcare_90_canonical),
  prior_visual_euro_selfcare_90_neutral = prediction_visual(m_prior_neutral_euro_selfcare_90_canonical),
  prior_visual_euro_selfcare_90_left = prediction_visual(m_prior_left_euro_selfcare_90_canonical),
  prior_visual_euro_selfcare_90_right = prediction_visual(m_prior_right_euro_selfcare_90_canonical),
  prior_visual_euro_selfcare_90_flat = prediction_visual(m_prior_flat_euro_selfcare_90_canonical),
  prior_check_euro_selfcare_180 = f_prior_predictive_check(m_prior_neutral_euro_selfcare_180_canonical, m_prior_left_euro_selfcare_180_canonical, m_prior_right_euro_selfcare_180_canonical, m_prior_flat_euro_selfcare_180_canonical),
  prior_visual_euro_selfcare_180_neutral = prediction_visual(m_prior_neutral_euro_selfcare_180_canonical),
  prior_visual_euro_selfcare_180_left = prediction_visual(m_prior_left_euro_selfcare_180_canonical),
  prior_visual_euro_selfcare_180_right = prediction_visual(m_prior_right_euro_selfcare_180_canonical),
  prior_visual_euro_selfcare_180_flat = prediction_visual(m_prior_flat_euro_selfcare_180_canonical),
  prior_check_euro_selfcare_365 = f_prior_predictive_check(m_prior_neutral_euro_selfcare_365_canonical, m_prior_left_euro_selfcare_365_canonical, m_prior_right_euro_selfcare_365_canonical, m_prior_flat_euro_selfcare_365_canonical),
  prior_visual_euro_selfcare_365_neutral = prediction_visual(m_prior_neutral_euro_selfcare_365_canonical),
  prior_visual_euro_selfcare_365_left = prediction_visual(m_prior_left_euro_selfcare_365_canonical),
  prior_visual_euro_selfcare_365_right = prediction_visual(m_prior_right_euro_selfcare_365_canonical),
  prior_visual_euro_selfcare_365_flat = prediction_visual(m_prior_flat_euro_selfcare_365_canonical),
  prior_check_euro_pain_90 = f_prior_predictive_check(m_prior_neutral_euro_pain_90_canonical, m_prior_left_euro_pain_90_canonical, m_prior_right_euro_pain_90_canonical, m_prior_flat_euro_pain_90_canonical),
  prior_visual_euro_pain_90_neutral = prediction_visual(m_prior_neutral_euro_pain_90_canonical),
  prior_visual_euro_pain_90_left = prediction_visual(m_prior_left_euro_pain_90_canonical),
  prior_visual_euro_pain_90_right = prediction_visual(m_prior_right_euro_pain_90_canonical),
  prior_visual_euro_pain_90_flat = prediction_visual(m_prior_flat_euro_pain_90_canonical),
  prior_check_euro_pain_180 = f_prior_predictive_check(m_prior_neutral_euro_pain_180_canonical, m_prior_left_euro_pain_180_canonical, m_prior_right_euro_pain_180_canonical, m_prior_flat_euro_pain_180_canonical),
  prior_visual_euro_pain_180_neutral = prediction_visual(m_prior_neutral_euro_pain_180_canonical),
  prior_visual_euro_pain_180_left = prediction_visual(m_prior_left_euro_pain_180_canonical),
  prior_visual_euro_pain_180_right = prediction_visual(m_prior_right_euro_pain_180_canonical),
  prior_visual_euro_pain_180_flat = prediction_visual(m_prior_flat_euro_pain_180_canonical),
  prior_check_euro_pain_365 = f_prior_predictive_check(m_prior_neutral_euro_pain_365_canonical, m_prior_left_euro_pain_365_canonical, m_prior_right_euro_pain_365_canonical, m_prior_flat_euro_pain_365_canonical),
  prior_visual_euro_pain_365_neutral = prediction_visual(m_prior_neutral_euro_pain_365_canonical),
  prior_visual_euro_pain_365_left = prediction_visual(m_prior_left_euro_pain_365_canonical),
  prior_visual_euro_pain_365_right = prediction_visual(m_prior_right_euro_pain_365_canonical),
  prior_visual_euro_pain_365_flat = prediction_visual(m_prior_flat_euro_pain_365_canonical),
  prior_check_euro_anxiety_90 = f_prior_predictive_check(m_prior_neutral_euro_anxiety_90_canonical, m_prior_left_euro_anxiety_90_canonical, m_prior_right_euro_anxiety_90_canonical, m_prior_flat_euro_anxiety_90_canonical),
  prior_visual_euro_anxiety_90_neutral = prediction_visual(m_prior_neutral_euro_anxiety_90_canonical),
  prior_visual_euro_anxiety_90_left = prediction_visual(m_prior_left_euro_anxiety_90_canonical),
  prior_visual_euro_anxiety_90_right = prediction_visual(m_prior_right_euro_anxiety_90_canonical),
  prior_visual_euro_anxiety_90_flat = prediction_visual(m_prior_flat_euro_anxiety_90_canonical),
  prior_check_euro_anxiety_180 = f_prior_predictive_check(m_prior_neutral_euro_anxiety_180_canonical, m_prior_left_euro_anxiety_180_canonical, m_prior_right_euro_anxiety_180_canonical, m_prior_flat_euro_anxiety_180_canonical),
  prior_visual_euro_anxiety_180_neutral = prediction_visual(m_prior_neutral_euro_anxiety_180_canonical),
  prior_visual_euro_anxiety_180_left = prediction_visual(m_prior_left_euro_anxiety_180_canonical),
  prior_visual_euro_anxiety_180_right = prediction_visual(m_prior_right_euro_anxiety_180_canonical),
  prior_visual_euro_anxiety_180_flat = prediction_visual(m_prior_flat_euro_anxiety_180_canonical),
  prior_check_euro_anxiety_365 = f_prior_predictive_check(m_prior_neutral_euro_anxiety_365_canonical, m_prior_left_euro_anxiety_365_canonical, m_prior_right_euro_anxiety_365_canonical, m_prior_flat_euro_anxiety_365_canonical),
  prior_visual_euro_anxiety_365_neutral = prediction_visual(m_prior_neutral_euro_anxiety_365_canonical),
  prior_visual_euro_anxiety_365_left = prediction_visual(m_prior_left_euro_anxiety_365_canonical),
  prior_visual_euro_anxiety_365_right = prediction_visual(m_prior_right_euro_anxiety_365_canonical),
  prior_visual_euro_anxiety_365_flat = prediction_visual(m_prior_flat_euro_anxiety_365_canonical),

  ### Posterior Simulation ----
  m_posterior_mrs_90_minimal = f_posterior_mrs_90_minimal(ich_aggressive),
  m_posterior_neutral_mrs_90_canonical = f_posterior_neutral_mrs_90_canonical(ich_aggressive),
  m_posterior_left_mrs_90_canonical = f_posterior_left_mrs_90_canonical(ich_aggressive),
  m_posterior_right_mrs_90_canonical = f_posterior_right_mrs_90_canonical(ich_aggressive),
  m_posterior_flat_mrs_90_canonical = f_posterior_flat_mrs_90_canonical(ich_aggressive),
  m_posterior_mrs_180_minimal = f_posterior_mrs_180_minimal(ich_aggressive),
  m_posterior_neutral_mrs_180_canonical = f_posterior_neutral_mrs_180_canonical(ich_aggressive),
  m_posterior_left_mrs_180_canonical = f_posterior_left_mrs_180_canonical(ich_aggressive),
  m_posterior_right_mrs_180_canonical = f_posterior_right_mrs_180_canonical(ich_aggressive),
  m_posterior_flat_mrs_180_canonical = f_posterior_flat_mrs_180_canonical(ich_aggressive),
  m_posterior_mrs_365_minimal = f_posterior_mrs_365_minimal(ich_aggressive),
  m_posterior_neutral_mrs_365_canonical = f_posterior_neutral_mrs_365_canonical(ich_aggressive),
  m_posterior_left_mrs_365_canonical = f_posterior_left_mrs_365_canonical(ich_aggressive),
  m_posterior_right_mrs_365_canonical = f_posterior_right_mrs_365_canonical(ich_aggressive),
  m_posterior_flat_mrs_365_canonical = f_posterior_flat_mrs_365_canonical(ich_aggressive),
  m_posterior_neutral_euro_mobility_90_canonical = f_posterior_neutral_euro_mobility_90_canonical(ich_aggressive),
  m_posterior_left_euro_mobility_90_canonical = f_posterior_left_euro_mobility_90_canonical(ich_aggressive),
  m_posterior_right_euro_mobility_90_canonical = f_posterior_right_euro_mobility_90_canonical(ich_aggressive),
  m_posterior_flat_euro_mobility_90_canonical = f_posterior_flat_euro_mobility_90_canonical(ich_aggressive),
  m_posterior_neutral_euro_mobility_180_canonical = f_posterior_neutral_euro_mobility_180_canonical(ich_aggressive),
  m_posterior_left_euro_mobility_180_canonical = f_posterior_left_euro_mobility_180_canonical(ich_aggressive),
  m_posterior_right_euro_mobility_180_canonical = f_posterior_right_euro_mobility_180_canonical(ich_aggressive),
  m_posterior_flat_euro_mobility_180_canonical = f_posterior_flat_euro_mobility_180_canonical(ich_aggressive),
  m_posterior_neutral_euro_mobility_365_canonical = f_posterior_neutral_euro_mobility_365_canonical(ich_aggressive),
  m_posterior_left_euro_mobility_365_canonical = f_posterior_left_euro_mobility_365_canonical(ich_aggressive),
  m_posterior_right_euro_mobility_365_canonical = f_posterior_right_euro_mobility_365_canonical(ich_aggressive),
  m_posterior_flat_euro_mobility_365_canonical = f_posterior_flat_euro_mobility_365_canonical(ich_aggressive),
  m_posterior_neutral_euro_selfcare_90_canonical = f_posterior_neutral_euro_selfcare_90_canonical(ich_aggressive),
  m_posterior_left_euro_selfcare_90_canonical = f_posterior_left_euro_selfcare_90_canonical(ich_aggressive),
  m_posterior_right_euro_selfcare_90_canonical = f_posterior_right_euro_selfcare_90_canonical(ich_aggressive),
  m_posterior_flat_euro_selfcare_90_canonical = f_posterior_flat_euro_selfcare_90_canonical(ich_aggressive),
  m_posterior_neutral_euro_selfcare_180_canonical = f_posterior_neutral_euro_selfcare_180_canonical(ich_aggressive),
  m_posterior_left_euro_selfcare_180_canonical = f_posterior_left_euro_selfcare_180_canonical(ich_aggressive),
  m_posterior_right_euro_selfcare_180_canonical = f_posterior_right_euro_selfcare_180_canonical(ich_aggressive),
  m_posterior_flat_euro_selfcare_180_canonical = f_posterior_flat_euro_selfcare_180_canonical(ich_aggressive),
  m_posterior_neutral_euro_selfcare_365_canonical = f_posterior_neutral_euro_selfcare_365_canonical(ich_aggressive),
  m_posterior_left_euro_selfcare_365_canonical = f_posterior_left_euro_selfcare_365_canonical(ich_aggressive),
  m_posterior_right_euro_selfcare_365_canonical = f_posterior_right_euro_selfcare_365_canonical(ich_aggressive),
  m_posterior_flat_euro_selfcare_365_canonical = f_posterior_flat_euro_selfcare_365_canonical(ich_aggressive),
  m_posterior_neutral_euro_usual_90_canonical = f_posterior_neutral_euro_usual_90_canonical(ich_aggressive),
  m_posterior_left_euro_usual_90_canonical = f_posterior_left_euro_usual_90_canonical(ich_aggressive),
  m_posterior_right_euro_usual_90_canonical = f_posterior_right_euro_usual_90_canonical(ich_aggressive),
  m_posterior_flat_euro_usual_90_canonical = f_posterior_flat_euro_usual_90_canonical(ich_aggressive),
  m_posterior_neutral_euro_usual_180_canonical = f_posterior_neutral_euro_usual_180_canonical(ich_aggressive),
  m_posterior_left_euro_usual_180_canonical = f_posterior_left_euro_usual_180_canonical(ich_aggressive),
  m_posterior_right_euro_usual_180_canonical = f_posterior_right_euro_usual_180_canonical(ich_aggressive),
  m_posterior_flat_euro_usual_180_canonical = f_posterior_flat_euro_usual_180_canonical(ich_aggressive),
  m_posterior_neutral_euro_usual_365_canonical = f_posterior_neutral_euro_usual_365_canonical(ich_aggressive),
  m_posterior_left_euro_usual_365_canonical = f_posterior_left_euro_usual_365_canonical(ich_aggressive),
  m_posterior_right_euro_usual_365_canonical = f_posterior_right_euro_usual_365_canonical(ich_aggressive),
  m_posterior_flat_euro_usual_365_canonical = f_posterior_flat_euro_usual_365_canonical(ich_aggressive),
  m_posterior_neutral_euro_pain_90_canonical = f_posterior_neutral_euro_pain_90_canonical(ich_aggressive),
  m_posterior_left_euro_pain_90_canonical = f_posterior_left_euro_pain_90_canonical(ich_aggressive),
  m_posterior_right_euro_pain_90_canonical = f_posterior_right_euro_pain_90_canonical(ich_aggressive),
  m_posterior_flat_euro_pain_90_canonical = f_posterior_flat_euro_pain_90_canonical(ich_aggressive),
  m_posterior_neutral_euro_pain_180_canonical = f_posterior_neutral_euro_pain_180_canonical(ich_aggressive),
  m_posterior_left_euro_pain_180_canonical = f_posterior_left_euro_pain_180_canonical(ich_aggressive),
  m_posterior_right_euro_pain_180_canonical = f_posterior_right_euro_pain_180_canonical(ich_aggressive),
  m_posterior_flat_euro_pain_180_canonical = f_posterior_flat_euro_pain_180_canonical(ich_aggressive),
  m_posterior_neutral_euro_pain_365_canonical = f_posterior_neutral_euro_pain_365_canonical(ich_aggressive),
  m_posterior_left_euro_pain_365_canonical = f_posterior_left_euro_pain_365_canonical(ich_aggressive),
  m_posterior_right_euro_pain_365_canonical = f_posterior_right_euro_pain_365_canonical(ich_aggressive),
  m_posterior_flat_euro_pain_365_canonical = f_posterior_flat_euro_pain_365_canonical(ich_aggressive),
  m_posterior_neutral_euro_anxiety_90_canonical = f_posterior_neutral_euro_anxiety_90_canonical(ich_aggressive),
  m_posterior_left_euro_anxiety_90_canonical = f_posterior_left_euro_anxiety_90_canonical(ich_aggressive),
  m_posterior_right_euro_anxiety_90_canonical = f_posterior_right_euro_anxiety_90_canonical(ich_aggressive),
  m_posterior_flat_euro_anxiety_90_canonical = f_posterior_flat_euro_anxiety_90_canonical(ich_aggressive),
  m_posterior_neutral_euro_anxiety_180_canonical = f_posterior_neutral_euro_anxiety_180_canonical(ich_aggressive),
  m_posterior_left_euro_anxiety_180_canonical = f_posterior_left_euro_anxiety_180_canonical(ich_aggressive),
  m_posterior_right_euro_anxiety_180_canonical = f_posterior_right_euro_anxiety_180_canonical(ich_aggressive),
  m_posterior_flat_euro_anxiety_180_canonical = f_posterior_flat_euro_anxiety_180_canonical(ich_aggressive),
  m_posterior_neutral_euro_anxiety_365_canonical = f_posterior_neutral_euro_anxiety_365_canonical(ich_aggressive),
  m_posterior_left_euro_anxiety_365_canonical = f_posterior_left_euro_anxiety_365_canonical(ich_aggressive),
  m_posterior_right_euro_anxiety_365_canonical = f_posterior_right_euro_anxiety_365_canonical(ich_aggressive),
  m_posterior_flat_euro_anxiety_365_canonical = f_posterior_flat_euro_anxiety_365_canonical(ich_aggressive),

  #### Posterior Diagnostics

  diag_posterior_mrs_90_minimal = posterior_diagnostics(m_posterior_mrs_90_minimal),
  diag_posterior_neutral_mrs_90_canonical = posterior_diagnostics(m_posterior_neutral_mrs_90_canonical),
  diag_posterior_left_mrs_90_canonical = posterior_diagnostics(m_posterior_left_mrs_90_canonical),
  diag_posterior_right_mrs_90_canonical = posterior_diagnostics(m_posterior_right_mrs_90_canonical),
  diag_posterior_flat_mrs_90_canonical = posterior_diagnostics(m_posterior_flat_mrs_90_canonical),
  diag_posterior_mrs_180_minimal = posterior_diagnostics(m_posterior_mrs_180_minimal),
  diag_posterior_neutral_mrs_180_canonical = posterior_diagnostics(m_posterior_neutral_mrs_180_canonical),
  diag_posterior_left_mrs_180_canonical = posterior_diagnostics(m_posterior_left_mrs_180_canonical),
  diag_posterior_right_mrs_180_canonical = posterior_diagnostics(m_posterior_right_mrs_180_canonical),
  diag_posterior_flat_mrs_180_canonical = posterior_diagnostics(m_posterior_flat_mrs_180_canonical),
  diag_posterior_mrs_365_minimal = posterior_diagnostics(m_posterior_mrs_365_minimal),
  diag_posterior_neutral_mrs_365_canonical = posterior_diagnostics(m_posterior_neutral_mrs_365_canonical),
  diag_posterior_left_mrs_365_canonical = posterior_diagnostics(m_posterior_left_mrs_365_canonical),
  diag_posterior_right_mrs_365_canonical = posterior_diagnostics(m_posterior_right_mrs_365_canonical),
  diag_posterior_flat_mrs_365_canonical = posterior_diagnostics(m_posterior_flat_mrs_365_canonical),
  diag_posterior_neutral_euro_mobility_90_canonical = posterior_diagnostics(m_posterior_neutral_euro_mobility_90_canonical),
  diag_posterior_left_euro_mobility_90_canonical = posterior_diagnostics(m_posterior_left_euro_mobility_90_canonical),
  diag_posterior_right_euro_mobility_90_canonical = posterior_diagnostics(m_posterior_right_euro_mobility_90_canonical),
  diag_posterior_flat_euro_mobility_90_canonical = posterior_diagnostics(m_posterior_flat_euro_mobility_90_canonical),
  diag_posterior_neutral_euro_mobility_180_canonical = posterior_diagnostics(m_posterior_neutral_euro_mobility_180_canonical),
  diag_posterior_left_euro_mobility_180_canonical = posterior_diagnostics(m_posterior_left_euro_mobility_180_canonical),
  diag_posterior_right_euro_mobility_180_canonical = posterior_diagnostics(m_posterior_right_euro_mobility_180_canonical),
  diag_posterior_flat_euro_mobility_180_canonical = posterior_diagnostics(m_posterior_flat_euro_mobility_180_canonical),
  diag_posterior_neutral_euro_mobility_365_canonical = posterior_diagnostics(m_posterior_neutral_euro_mobility_365_canonical),
  diag_posterior_left_euro_mobility_365_canonical = posterior_diagnostics(m_posterior_left_euro_mobility_365_canonical),
  diag_posterior_right_euro_mobility_365_canonical = posterior_diagnostics(m_posterior_right_euro_mobility_365_canonical),
  diag_posterior_flat_euro_mobility_365_canonical = posterior_diagnostics(m_posterior_flat_euro_mobility_365_canonical),
  diag_posterior_neutral_euro_selfcare_90_canonical = posterior_diagnostics(m_posterior_neutral_euro_selfcare_90_canonical),
  diag_posterior_left_euro_selfcare_90_canonical = posterior_diagnostics(m_posterior_left_euro_selfcare_90_canonical),
  diag_posterior_right_euro_selfcare_90_canonical = posterior_diagnostics(m_posterior_right_euro_selfcare_90_canonical),
  diag_posterior_flat_euro_selfcare_90_canonical = posterior_diagnostics(m_posterior_flat_euro_selfcare_90_canonical),
  diag_posterior_neutral_euro_selfcare_180_canonical = posterior_diagnostics(m_posterior_neutral_euro_selfcare_180_canonical),
  diag_posterior_left_euro_selfcare_180_canonical = posterior_diagnostics(m_posterior_left_euro_selfcare_180_canonical),
  diag_posterior_right_euro_selfcare_180_canonical = posterior_diagnostics(m_posterior_right_euro_selfcare_180_canonical),
  diag_posterior_flat_euro_selfcare_180_canonical = posterior_diagnostics(m_posterior_flat_euro_selfcare_180_canonical),
  diag_posterior_neutral_euro_selfcare_365_canonical = posterior_diagnostics(m_posterior_neutral_euro_selfcare_365_canonical),
  diag_posterior_left_euro_selfcare_365_canonical = posterior_diagnostics(m_posterior_left_euro_selfcare_365_canonical),
  diag_posterior_right_euro_selfcare_365_canonical = posterior_diagnostics(m_posterior_right_euro_selfcare_365_canonical),
  diag_posterior_flat_euro_selfcare_365_canonical = posterior_diagnostics(m_posterior_flat_euro_selfcare_365_canonical),
  diag_posterior_neutral_euro_usual_90_canonical = posterior_diagnostics(m_posterior_neutral_euro_usual_90_canonical),
  diag_posterior_left_euro_usual_90_canonical = posterior_diagnostics(m_posterior_left_euro_usual_90_canonical),
  diag_posterior_right_euro_usual_90_canonical = posterior_diagnostics(m_posterior_right_euro_usual_90_canonical),
  diag_posterior_flat_euro_usual_90_canonical = posterior_diagnostics(m_posterior_flat_euro_usual_90_canonical),
  diag_posterior_neutral_euro_usual_180_canonical = posterior_diagnostics(m_posterior_neutral_euro_usual_180_canonical),
  diag_posterior_left_euro_usual_180_canonical = posterior_diagnostics(m_posterior_left_euro_usual_180_canonical),
  diag_posterior_right_euro_usual_180_canonical = posterior_diagnostics(m_posterior_right_euro_usual_180_canonical),
  diag_posterior_flat_euro_usual_180_canonical = posterior_diagnostics(m_posterior_flat_euro_usual_180_canonical),
  diag_posterior_neutral_euro_usual_365_canonical = posterior_diagnostics(m_posterior_neutral_euro_usual_365_canonical),
  diag_posterior_left_euro_usual_365_canonical = posterior_diagnostics(m_posterior_left_euro_usual_365_canonical),
  diag_posterior_right_euro_usual_365_canonical = posterior_diagnostics(m_posterior_right_euro_usual_365_canonical),
  diag_posterior_flat_euro_usual_365_canonical = posterior_diagnostics(m_posterior_flat_euro_usual_365_canonical),
  diag_posterior_neutral_euro_pain_90_canonical = posterior_diagnostics(m_posterior_neutral_euro_pain_90_canonical),
  diag_posterior_left_euro_pain_90_canonical = posterior_diagnostics(m_posterior_left_euro_pain_90_canonical),
  diag_posterior_right_euro_pain_90_canonical = posterior_diagnostics(m_posterior_right_euro_pain_90_canonical),
  diag_posterior_flat_euro_pain_90_canonical = posterior_diagnostics(m_posterior_flat_euro_pain_90_canonical),
  diag_posterior_neutral_euro_pain_180_canonical = posterior_diagnostics(m_posterior_neutral_euro_pain_180_canonical),
  diag_posterior_left_euro_pain_180_canonical = posterior_diagnostics(m_posterior_left_euro_pain_180_canonical),
  diag_posterior_right_euro_pain_180_canonical = posterior_diagnostics(m_posterior_right_euro_pain_180_canonical),
  diag_posterior_flat_euro_pain_180_canonical = posterior_diagnostics(m_posterior_flat_euro_pain_180_canonical),
  diag_posterior_neutral_euro_pain_365_canonical = posterior_diagnostics(m_posterior_neutral_euro_pain_365_canonical),
  diag_posterior_left_euro_pain_365_canonical = posterior_diagnostics(m_posterior_left_euro_pain_365_canonical),
  diag_posterior_right_euro_pain_365_canonical = posterior_diagnostics(m_posterior_right_euro_pain_365_canonical),
  diag_posterior_flat_euro_pain_365_canonical = posterior_diagnostics(m_posterior_flat_euro_pain_365_canonical),
  diag_posterior_neutral_euro_anxiety_90_canonical = posterior_diagnostics(m_posterior_neutral_euro_anxiety_90_canonical),
  diag_posterior_left_euro_anxiety_90_canonical = posterior_diagnostics(m_posterior_left_euro_anxiety_90_canonical),
  diag_posterior_right_euro_anxiety_90_canonical = posterior_diagnostics(m_posterior_right_euro_anxiety_90_canonical),
  diag_posterior_flat_euro_anxiety_90_canonical = posterior_diagnostics(m_posterior_flat_euro_anxiety_90_canonical),
  diag_posterior_neutral_euro_anxiety_180_canonical = posterior_diagnostics(m_posterior_neutral_euro_anxiety_180_canonical),
  diag_posterior_left_euro_anxiety_180_canonical = posterior_diagnostics(m_posterior_left_euro_anxiety_180_canonical),
  diag_posterior_right_euro_anxiety_180_canonical = posterior_diagnostics(m_posterior_right_euro_anxiety_180_canonical),
  diag_posterior_flat_euro_anxiety_180_canonical = posterior_diagnostics(m_posterior_flat_euro_anxiety_180_canonical),
  diag_posterior_neutral_euro_anxiety_365_canonical = posterior_diagnostics(m_posterior_neutral_euro_anxiety_365_canonical),
  diag_posterior_left_euro_anxiety_365_canonical = posterior_diagnostics(m_posterior_left_euro_anxiety_365_canonical),
  diag_posterior_right_euro_anxiety_365_canonical = posterior_diagnostics(m_posterior_right_euro_anxiety_365_canonical),
  diag_posterior_flat_euro_anxiety_365_canonical = posterior_diagnostics(m_posterior_flat_euro_anxiety_365_canonical),
  post_pred_check_mrs_90_minimal = f_post_predictive_check(m_posterior_mrs_90_minimal),
  post_pred_check_neutral_mrs_90_canonical = f_post_predictive_check(m_posterior_neutral_mrs_90_canonical),
  post_pred_check_left_mrs_90_canonical = f_post_predictive_check(m_posterior_left_mrs_90_canonical),
  post_pred_check_right_mrs_90_canonical = f_post_predictive_check(m_posterior_right_mrs_90_canonical),
  post_pred_check_flat_mrs_90_canonical = f_post_predictive_check(m_posterior_flat_mrs_90_canonical),
  post_pred_check_mrs_180_minimal = f_post_predictive_check(m_posterior_mrs_180_minimal),
  post_pred_check_neutral_mrs_180_canonical = f_post_predictive_check(m_posterior_neutral_mrs_180_canonical),
  post_pred_check_left_mrs_180_canonical = f_post_predictive_check(m_posterior_left_mrs_180_canonical),
  post_pred_check_right_mrs_180_canonical = f_post_predictive_check(m_posterior_right_mrs_180_canonical),
  post_pred_check_flat_mrs_180_canonical = f_post_predictive_check(m_posterior_flat_mrs_180_canonical),
  post_pred_check_mrs_365_minimal = f_post_predictive_check(m_posterior_mrs_365_minimal),
  post_pred_check_neutral_mrs_365_canonical = f_post_predictive_check(m_posterior_neutral_mrs_365_canonical),
  post_pred_check_left_mrs_365_canonical = f_post_predictive_check(m_posterior_left_mrs_365_canonical),
  post_pred_check_right_mrs_365_canonical = f_post_predictive_check(m_posterior_right_mrs_365_canonical),
  post_pred_check_flat_mrs_365_canonical = f_post_predictive_check(m_posterior_flat_mrs_365_canonical),
  post_pred_check_neutral_euro_mobility_90_canonical = f_post_predictive_check(m_posterior_neutral_euro_mobility_90_canonical),
  post_pred_check_left_euro_mobility_90_canonical = f_post_predictive_check(m_posterior_left_euro_mobility_90_canonical),
  post_pred_check_right_euro_mobility_90_canonical = f_post_predictive_check(m_posterior_right_euro_mobility_90_canonical),
  post_pred_check_flat_euro_mobility_90_canonical = f_post_predictive_check(m_posterior_flat_euro_mobility_90_canonical),
  post_pred_check_neutral_euro_mobility_180_canonical = f_post_predictive_check(m_posterior_neutral_euro_mobility_180_canonical),
  post_pred_check_left_euro_mobility_180_canonical = f_post_predictive_check(m_posterior_left_euro_mobility_180_canonical),
  post_pred_check_right_euro_mobility_180_canonical = f_post_predictive_check(m_posterior_right_euro_mobility_180_canonical),
  post_pred_check_flat_euro_mobility_180_canonical = f_post_predictive_check(m_posterior_flat_euro_mobility_180_canonical),
  post_pred_check_neutral_euro_mobility_365_canonical = f_post_predictive_check(m_posterior_neutral_euro_mobility_365_canonical),
  post_pred_check_left_euro_mobility_365_canonical = f_post_predictive_check(m_posterior_left_euro_mobility_365_canonical),
  post_pred_check_right_euro_mobility_365_canonical = f_post_predictive_check(m_posterior_right_euro_mobility_365_canonical),
  post_pred_check_flat_euro_mobility_365_canonical = f_post_predictive_check(m_posterior_flat_euro_mobility_365_canonical),
  post_pred_check_neutral_euro_selfcare_90_canonical = f_post_predictive_check(m_posterior_neutral_euro_selfcare_90_canonical),
  post_pred_check_left_euro_selfcare_90_canonical = f_post_predictive_check(m_posterior_left_euro_selfcare_90_canonical),
  post_pred_check_right_euro_selfcare_90_canonical = f_post_predictive_check(m_posterior_right_euro_selfcare_90_canonical),
  post_pred_check_flat_euro_selfcare_90_canonical = f_post_predictive_check(m_posterior_flat_euro_selfcare_90_canonical),
  post_pred_check_neutral_euro_selfcare_180_canonical = f_post_predictive_check(m_posterior_neutral_euro_selfcare_180_canonical),
  post_pred_check_left_euro_selfcare_180_canonical = f_post_predictive_check(m_posterior_left_euro_selfcare_180_canonical),
  post_pred_check_right_euro_selfcare_180_canonical = f_post_predictive_check(m_posterior_right_euro_selfcare_180_canonical),
  post_pred_check_flat_euro_selfcare_180_canonical = f_post_predictive_check(m_posterior_flat_euro_selfcare_180_canonical),
  post_pred_check_neutral_euro_selfcare_365_canonical = f_post_predictive_check(m_posterior_neutral_euro_selfcare_365_canonical),
  post_pred_check_left_euro_selfcare_365_canonical = f_post_predictive_check(m_posterior_left_euro_selfcare_365_canonical),
  post_pred_check_right_euro_selfcare_365_canonical = f_post_predictive_check(m_posterior_right_euro_selfcare_365_canonical),
  post_pred_check_flat_euro_selfcare_365_canonical = f_post_predictive_check(m_posterior_flat_euro_selfcare_365_canonical),
  post_pred_check_neutral_euro_usual_90_canonical = f_post_predictive_check(m_posterior_neutral_euro_usual_90_canonical),
  post_pred_check_left_euro_usual_90_canonical = f_post_predictive_check(m_posterior_left_euro_usual_90_canonical),
  post_pred_check_right_euro_usual_90_canonical = f_post_predictive_check(m_posterior_right_euro_usual_90_canonical),
  post_pred_check_flat_euro_usual_90_canonical = f_post_predictive_check(m_posterior_flat_euro_usual_90_canonical),
  post_pred_check_neutral_euro_usual_180_canonical = f_post_predictive_check(m_posterior_neutral_euro_usual_180_canonical),
  post_pred_check_left_euro_usual_180_canonical = f_post_predictive_check(m_posterior_left_euro_usual_180_canonical),
  post_pred_check_right_euro_usual_180_canonical = f_post_predictive_check(m_posterior_right_euro_usual_180_canonical),
  post_pred_check_flat_euro_usual_180_canonical = f_post_predictive_check(m_posterior_flat_euro_usual_180_canonical),
  post_pred_check_neutral_euro_usual_365_canonical = f_post_predictive_check(m_posterior_neutral_euro_usual_365_canonical),
  post_pred_check_left_euro_usual_365_canonical = f_post_predictive_check(m_posterior_left_euro_usual_365_canonical),
  post_pred_check_right_euro_usual_365_canonical = f_post_predictive_check(m_posterior_right_euro_usual_365_canonical),
  post_pred_check_flat_euro_usual_365_canonical = f_post_predictive_check(m_posterior_flat_euro_usual_365_canonical),
  post_pred_check_neutral_euro_pain_90_canonical = f_post_predictive_check(m_posterior_neutral_euro_pain_90_canonical),
  post_pred_check_left_euro_pain_90_canonical = f_post_predictive_check(m_posterior_left_euro_pain_90_canonical),
  post_pred_check_right_euro_pain_90_canonical = f_post_predictive_check(m_posterior_right_euro_pain_90_canonical),
  post_pred_check_flat_euro_pain_90_canonical = f_post_predictive_check(m_posterior_flat_euro_pain_90_canonical),
  post_pred_check_neutral_euro_pain_180_canonical = f_post_predictive_check(m_posterior_neutral_euro_pain_180_canonical),
  post_pred_check_left_euro_pain_180_canonical = f_post_predictive_check(m_posterior_left_euro_pain_180_canonical),
  post_pred_check_right_euro_pain_180_canonical = f_post_predictive_check(m_posterior_right_euro_pain_180_canonical),
  post_pred_check_flat_euro_pain_180_canonical = f_post_predictive_check(m_posterior_flat_euro_pain_180_canonical),
  post_pred_check_neutral_euro_pain_365_canonical = f_post_predictive_check(m_posterior_neutral_euro_pain_365_canonical),
  post_pred_check_left_euro_pain_365_canonical = f_post_predictive_check(m_posterior_left_euro_pain_365_canonical),
  post_pred_check_right_euro_pain_365_canonical = f_post_predictive_check(m_posterior_right_euro_pain_365_canonical),
  post_pred_check_flat_euro_pain_365_canonical = f_post_predictive_check(m_posterior_flat_euro_pain_365_canonical),
  post_pred_check_neutral_euro_anxiety_90_canonical = f_post_predictive_check(m_posterior_neutral_euro_anxiety_90_canonical),
  post_pred_check_left_euro_anxiety_90_canonical = f_post_predictive_check(m_posterior_left_euro_anxiety_90_canonical),
  post_pred_check_right_euro_anxiety_90_canonical = f_post_predictive_check(m_posterior_right_euro_anxiety_90_canonical),
  post_pred_check_flat_euro_anxiety_90_canonical = f_post_predictive_check(m_posterior_flat_euro_anxiety_90_canonical),
  post_pred_check_neutral_euro_anxiety_180_canonical = f_post_predictive_check(m_posterior_neutral_euro_anxiety_180_canonical),
  post_pred_check_left_euro_anxiety_180_canonical = f_post_predictive_check(m_posterior_left_euro_anxiety_180_canonical),
  post_pred_check_right_euro_anxiety_180_canonical = f_post_predictive_check(m_posterior_right_euro_anxiety_180_canonical),
  post_pred_check_flat_euro_anxiety_180_canonical = f_post_predictive_check(m_posterior_flat_euro_anxiety_180_canonical),
  post_pred_check_neutral_euro_anxiety_365_canonical = f_post_predictive_check(m_posterior_neutral_euro_anxiety_365_canonical),
  post_pred_check_left_euro_anxiety_365_canonical = f_post_predictive_check(m_posterior_left_euro_anxiety_365_canonical),
  post_pred_check_right_euro_anxiety_365_canonical = f_post_predictive_check(m_posterior_right_euro_anxiety_365_canonical),
  post_pred_check_flat_euro_anxiety_365_canonical = f_post_predictive_check(m_posterior_flat_euro_anxiety_365_canonical),

  ## Output and Reports ----
  table1 = table_1_function(ich_aggressive),
  # table1_docx <- gt::gtsave(table1, here("manuscripts", "table1.docx")), # For some reason have to MANUALLY run this!!!
  neutral_aggressive_models = models_list_func(
    m_posterior_neutral_neurosurgery,
    m_posterior_neutral_evd,
    m_posterior_neutral_days_mechanical_ventilation,
    m_posterior_neutral_tracheostomy,
    m_posterior_neutral_comfort,
    m_posterior_neutral_early_wlst,
    m_posterior_neutral_dnr_binary
  ),
  left_aggressive_models = models_list_func(
    m_posterior_left_neurosurgery,
    m_posterior_left_evd,
    m_posterior_left_days_mechanical_ventilation,
    m_posterior_left_tracheostomy,
    m_posterior_left_comfort,
    m_posterior_left_early_wlst,
    m_posterior_left_dnr_binary
  ),
  right_aggressive_models = models_list_func(
    m_posterior_right_neurosurgery,
    m_posterior_right_evd,
    m_posterior_right_days_mechanical_ventilation,
    m_posterior_right_tracheostomy,
    m_posterior_right_comfort,
    m_posterior_right_early_wlst,
    m_posterior_right_dnr_binary
  ),
  flat_aggressive_models = models_list_func(
    m_posterior_flat_neurosurgery,
    m_posterior_flat_evd,
    m_posterior_flat_days_mechanical_ventilation,
    m_posterior_flat_tracheostomy,
    m_posterior_flat_comfort,
    m_posterior_flat_early_wlst,
    m_posterior_flat_dnr_binary
  ),
  table2_neutral = table_2_function(ich_aggressive, neutral_aggressive_models),
  table2_left = table_2_function(ich_aggressive, left_aggressive_models),
  table2_right = table_2_function(ich_aggressive, right_aggressive_models),
  table2_flat = table_2_function(ich_aggressive, flat_aggressive_models),
  table2_docx = gtsave(table2_neutral, here("manuscripts", "table2.docx")),
  figure_1 = subgroup_figure_function(m_posterior_neutral_neurosurgery),
  figure_1_tiff = ggsave(here("manuscripts", "figure1.tiff"),
    plot = figure_1, height = 20, width = 14, dpi = 600
  ),
  figure_1_svg = ggsave(here("manuscripts", "figure1.svg"),
    plot = figure_1, height = 20, width = 14, dpi = 600
  ),
  figure_1_png = ggsave(here("manuscripts", "figure1.png"),
    plot = figure_1, height = 20, width = 14, dpi = 600
  ),
  neutral_outcome_models <- outcome_models_list_func(
    m_posterior_neutral_mrs_90_canonical,
    m_posterior_neutral_euro_mobility_90_canonical,
    m_posterior_neutral_euro_selfcare_90_canonical,
    m_posterior_neutral_euro_usual_90_canonical,
    m_posterior_neutral_euro_pain_90_canonical,
    m_posterior_neutral_euro_anxiety_90_canonical
  )

  # tar_quarto(
  #   table_1,
  #   here("manuscripts", "test.qmd")
  # )
)
