---
title: Differences in care for patients experiencing left vs. right hemisphere ICH
subtitle: Prior Predictive Checks
author: Nikhil Patel, MD
format:
  html: 
    mainfont: Figtree
    monofont: Source Code Pro
    embed-resources: true
    toc: true
    toc-location: left
    toc-depth: 6
    toc-title: Contents
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    code-overflow: wrap
    code-tools: true
    code-fold: true
    highlight-style: nord
---

```{r setup, output=FALSE, message=FALSE, warning=FALSE}
library(targets)
library(tidyverse)
library(glue)
library(marginaleffects)
library(modelsummary)
library(ggdist)
library(gghalves)
library(scales)
library(systemfonts)

# theme customization
theme_set(theme_minimal(base_family = "Figtree"))

# Format things as percentage points
label_pp <- label_number(
  accuracy = 1, scale = 100,
  suffix = " pp.", style_negative = "minus"
)

label_pp_tiny <- label_number(
  accuracy = 0.01, scale = 100,
  suffix = " pp.", style_negative = "minus"
)

# load targets objects
tar_load(model_parameters)
tar_load(prior_neurosurgery_minimal)
tar_load(prior_neurosurgery_canonical)
tar_load(prior_evd_minimal)
tar_load(prior_evd_canonical)
tar_load(prior_trach_minimal)
tar_load(prior_trach_canonical)
tar_load(prior_vent_minimal)
tar_load(prior_vent_canonical)

# prior functions

prior_printing <- function(x, y, var) {
  p1 <- model_parameters$priors[x]

  p2 <- y

  p3 <- predictions(y, by = "ich_laterality") |>
    as_tibble()

  p4 <- avg_comparisons(y, variables = "ich_laterality") |>
    posterior_draws() |>
    ggplot(aes(x = draw)) +
    stat_halfeye(
      .width = c(0.8, 0.95), point_interval = "median_hdi",
      fill = "#bc3032"
    ) +
    scale_x_continuous(labels = label_pp) +
    labs(
      title = "Prior Predictive Check",
      x = paste("Effect of hemispheric laterality\n on the probability of", {{ var }}),
      y = NULL, caption = "80% and 95% credible intervals shown in black"
    )

  return(list(
    priors = p1,
    model = p2,
    predictions = p3,
    plot = p4
  ))
}

```

## Prior Predictive Checks

### Neurosurgical Intervention

#### Minimal Model

```{r}

prior_printing("neurosurgery_minimal", prior_neurosurgery_minimal, "receiving neurosurgical intervention")

```
  
 
#### Canonical Model
  
```{r}

prior_printing("neurosurgery_canonical", prior_neurosurgery_canonical, "receiving neurosurgical intervention")

```

### EVD

#### Minimal Model

```{r}

prior_printing("evd_minimal", prior_evd_minimal, "receiving an EVD")

```

#### Canonical Model

```{r}

prior_printing("evd_canonical", prior_evd_canonical, "receiving an EVD")


```

### Tracheostomy

#### Minimal Model

```{r}

prior_printing("trach_minimal", prior_trach_minimal, "receiving an tracheostomy")

```

#### Canonical Model

```{r}

prior_printing("trach_canonical", prior_trach_canonical, "receiving a tracheostomy")

```

### Days of Mechanical Ventilation

#### Minimal Model

```{r}

prior_printing("vent_minimal", prior_vent_minimal, "number of days of mechanical ventilation")

```

#### Canonical Model

```{r}

prior_printing("vent_canonical", prior_vent_canonical, "number of days of mechanical ventilation")

```