project:
  type: website
  preview:
    port: 5555
    browser: false

website:
  title: "Hemispheric Laterality in ICH"
  navbar:
    search: true
    right:
      - href: manuscript1.qmd
        text: Manuscript
      - href: manuscript1_supplement.qmd
        text: Supplement
      - icon: github
        href: https://https://github.com/nikhilpatelmd/ich-laterality
        aria-label: GitHub

format:
  html:
    css: styles.css
    highlight-style: nord
    toc: true
    bibliography: references.bib
    csl: american-heart-association.csl
    mainfont: Figtree
    monofont: Source Code Pro