project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    theme: litera
    toc-location: left
    comments:
      hypothesis: true
    citations-hover: true
    crossrefs-hover: true
  # docx: default
  # jats: default

  # (other formats)
  # pdf: default

execute:
  freeze: true



