---
title: Patients with Left Hemispheric Intracerebral Hemorrhage are Less Likely to Receive Neurosurgical Intervention
subtitle: A Post Hoc Bayesian Analysis using data from ATACH-2 and ERICH
authors:
  - name: Nikhil Patel
    orcid: 0000-0002-3193-8590
    affiliation: Department of Internal Medicine, Wake Forest University School of Medicine
    roles: data analysis, writing
    corresponding: true
  - name: Matt Jaffa
    affiliation: Department of Neurology, University of Connecticut School of Medicine
  - name: Rahul Karamchandani
    affiliation: Department of Neurology, Wake Forest University School of Medicine
  - name: Andrew Asimos
    affiliation: Department of Emergency Medicine, Wake Forest University School of Medicine
  - name: Jonathan Parish
    affiliation: Carolina Neurosurgery & Spine Associates
  - name: Nicholas Allen Morris
    affiliation: Department of Neurology, University of Maryland School of Medicine
date: last-modified
format:
  html:
    embed-resources: true
  docx: default
abstract: |
bibliography: references.bib
csl: american-heart-association.csl
table-of-contents: true
toc-title: Contents
---

```{r setup}
#| echo: false
#| output: false
#| fig-height: 12

library(targets)
library(tidyverse)
library(withr)
library(here)

# load data
with_dir(here(), tar_load(ich_aggressive))

## patient counts
sample_size <- count(ich_aggressive)

left_hemisphere_count <- ich_aggressive |>
  filter(ich_laterality == "Left") |>
  count()

erich_count <- ich_aggressive |>
  filter(study == "ERICH") |>
  count()

atach_count <- ich_aggressive |>
  filter(study == "ATACH-2") |>
  count()

## table 2
with_dir(here(), tar_load(table2_neutral))
tibble2 <- table2_neutral[[1]]


```

## Introduction
Intracerebral hemorrhage (ICH) remains a challenging disease, marked by its sudden onset, morbidity, and mortality. While ischemic stroke has garnered considerable attention and therapeutic advancements, the acute management of ICH remains limited to blood pressure control, coagulopathy reversal, and more recently surgical evacuation of hemorrhage [@pradillaTrialEarlyMinimally2024]. Overwhelmingly these efforts have focused on reducing mortality and preventing additional morbidity due to secondary injury.

Clinical presentations for patients with stroke are varied based on the hemisphere affected, where hemispheric dominance dictates cognitive processing, attention, language, and emotional responses. Consequently, when confronted with the occurrence of ICH, the specific hemisphere affected can profoundly influence not only the clinical presentation but also therapeutic strategies and prognostic outcomes.

Previous research involving patients with ischemic stroke provide evidence that those with right hemispheric injury present later to the hospital and may not be treated as frequently with thrombolytic therapy. [@dileggeImpactLesionSide2005; @foerchDifferenceRecognitionRight2005; @portegiesLeftsidedStrokesAre2015;  @liStrokeLateralizationLarge2021] It has also been noted that there is a hesitation among some practitioners to offer decompressive craniectomy in patients with left dominant-hemispheric ischemic infarcts despite literature demonstrating that long-term functional outcomes and health-related quality of life (HRQoL) are equivalent if not better for patients with left hemispheric injuries. [@deb-chatterjiSideMattersDifferences2022; @leggeNeglectingDifference2006; @beuscherFunctionalLongTermOutcome2017; @satoHigherMortalityPatients2015]

Previous work has demonstrated mixed results with regard to hemispheric lateralization and outcomes in ICH, and there hasn't been much research examining if patients are treated differently based on the hemisphere affected. We aimed to evaluate the effect of hemispheric lateralization of ICH on likelihood of receiving aggressive surgical intervention as well as it's association with functional outcomes. 

## Methods

### Study Design and Participants
We conducted a post-hoc analysis using data from 2 prospective studies: the Antihypertensive Treatment of Acute Cerebral Hemorrhage II (ATACH-2) trial [@qureshiIntensiveBloodPressureLowering2016] and the Ethnic/Racial Variations of Intracerebral Hemorrhage (ERICH) [@wooEthnicRacialVariations2013] study. ATACH-2 was a large, multicenter, international, open-label, blinded-endpoint randomized controlled trial enrolling 1000 patients with ICH and randomizing them to either intesive blood pressure control (110-139 mm Hg) or standard blood pressure control (140-179 mm Hg). ERICH was a large, multicenter, prospective observational study enrolling patients in the United States admitted with ICH. Protocols and results of both studies have been previously published.

We included all patients enrolled in these two studies with supratentorial location of ICH. We excluded patients with cerebellar or brainstem ICH as well as any patient with primary intraventricular hemorrhage (IVH).

The study was approved by the institutional review board of the Wake Forest School of Medicine (IRB00098198).

### Exposures and Outcomes
Our exposure was hemispheric laterality (left versus right). Our primary outcome was neurosurgical intervention as a binary variable defined as receiving a hematoma evacuation, decompressive craniectomy, or other craniotomy.

To explore differences in other aspects of aggressive care, we defined several secondary outcomes: receipt of external ventricular drain (EVD), receipt of tracheostomy, days of mechanical ventilation, receipt of do-not-resuscitate (DNR) order at any point in the hospitalization, withdrawal of life-sustaining therapy (WLST) at any point in the hospitalization, and early WLST (defined as < 72 from symptom onset).

Our primary functional outcome was modified Rankin score (mRS) at 90 days. We also examined quality of life as assessed by the European Quality of Life-5 dimensions (EQ-5D) questionnaire.

### Statistical Analysis
To estimate the effect of hemispheric laterality on the outcomes of interest, we fitted hierarchal Bayesian regression models adjusted for the specified covariates below and study as a random intercept. This report follows suggestions from the Bayesian Analysis Reporting Guidelines. [@kruschkeBayesianAnalysisReporting2021] For binary endpoints, hierarchal Bayesian logistic regression models were used. For ordinal endpoints, hierarchal Bayesian ordinal logisitic regression models were used. All analyses were performed in R version 4.4.2 (R Foundation for Statistical Computing, Vienna, Austria) using the 'brms' and 'tidybayes' packages.

#### Covariate Selection
We constructed directed acyclic graphs (DAGs) to model our causal assumptions and to appropriately select variables to minimize confounding and selection bias. [@] Based on our specifications, we included the following covariates in our models: age, admission Glasgow coma score (GCS), ICH location (categorized as lobar, thalamic, or basal ganglia), baseline ICH volume (measured in millilters), and presence of intraventricular hemorrhage (IVH). The DAGs used in the analyses are available in the supplementary material.

#### Prior Distribution Specification
Four sets of priors were applied for all models: all assuming no association of hemispheric laterality on the outcomes of interest: 1) default, weakly informative priors as defined by the 'brms' software package; 2) priors informed from review of previous literature. A description of the reasons for these priors is available in the supplementary material.

#### Computation and Description of the Posterior Distribution
We report the following metrics for the effect of hemispheric laterality on the primary and secondary outcomes: 1) median odds ratio (OR) of the posterior distribution with 95% credible interval; 2) probability of any difference (P[OR] > 1); 3) probability of a substantial difference (P[OR] > 1.2) as defined by the study authors; 4) percent of the posterior distribution outside of the region of practical equivalence as defined by the study authors (ROPE; 0.95 > P[OR] > 1.05). A description of the rationale for these thresholds is available in the supplementary material.

#### Missing Data Treatment
MICE?

#### Sensitivity Analyses
1) different priors
2) alternate adjustment sets
3) missing data treatment?

### Data Availability Statement
The ATACH-2 (PI: Adnan I. Qureshi, MD, NCT01176565) and ERICH (PI: Daniel Woo, MD, MS, NCT01202864) data and analyses presented in this manuscript are based on the research files downloaded from the Archived Clinical Research web site of the National Institute of Neurologic Disease and Stroke (NINDS). The datasets can be obtained after approval of a written proposal as outlined on the NINDS website. As outlined in the NINDS Data Request Agreement, the analysis code is publicly available at [https://github.com/nikhilpatelmd/ich-laterality](https://github.com/nikhilpatelmd/ich-laterality).

## Results

### Baseline Characteristics
A total of `r sample_size` patients were included in the analysis, of which `r left_hemisphere_count` (`r percent(left_hemisphere_count/sample_size, digits = 1)`) had left hemispheric ICH (Table 1). They had higher NIHSS scores, lower GCS scores, and lower rates of hypertension as compared to those with right hemispheric ICH. There were `r erich_count` (`r percent(erich_count/sample_size, digits = 1)`) patients in the cohort from ERICH and `r atach_count` (`r percent(atach_count/sample_size, digits = 1)`) from ATACH-2.

### Left hemispheric ICH and neurosurgical intervention
Associations between hemispheric laterality and primary and secondary outcomes are shown in Table 2. There were 86 patients (5.0%) with left hemispheric ICH who underwent neurosurgical intervention as compared to 144 patients (8.2%) with right hemispheric ICH (aOR 1.79, 95% credible interval 1.33 - 2.41).  The posterior probability that the aOR was greater than 1 was 100%. The posterior probability of the aOR being greater than 1.2, indicating a substantial difference, was 100%. The 95% credible interval was entirely outside of the ROPE, suggesting a clinically meaningful difference in the odds of undergoing neurosurgical intervention between the two groups.

The results using the different predefined priors were consistent with the findings in the main model (Figure 1). Sensitivity analyses yielded similar results (Supplemental Appendix).

### Left hemispheric ICH and secondary outcomes
A total of 236 patients (13.7%) with left hemispheric ICH had an external ventricular drain placed as compared to 272 patients (15.5%) with right hemispheric ICH (aOR 1.29, 95% credible interval 1.05 - 1.59). The posterior probability that the aOR was greater than 1 was 99%. The posterior probability that the aOR was greater than 1.2 was 76%. The 95% credible interval was almost entirely outside of the ROPE (defined as 0.95 > aOR > 1.05).

Other secondary outcomes showed smaller and less certain associations with hemispheric laterality. 

### Left hemispheric ICH and functional outcomes
The associations between mRS at 90 days and functional outcomes are described in Table 3. The aOR for a worse mRS score at 90 days associated with right hemispheric ICH compared to left hemispheric ICH was 1.18 (95% credible interval: 1.02 to 1.37). The posterior probability that the aOR was > 1 was 99%, with 6% of the 95% credible interval was within the ROPE. The posterior probability that the aOR was > 1.2 was 43%.

When examining HRQOL, the largest differences between groups was in the Moblity and Self-Care domains. The aOR for a worse EuroQOL - Moblity score associated with right hemispheric ICH compared to left hemispheric ICH was 1.44 (95% credible interval 1.2 - 1.71) with similar results for the Self-Care domain. The posterior probability that the aOR was > 1 was 100% for both domains, with the posterior probability that the aOR was > 1.2 being 98%.

Results from using different priors and sensitivity analyses are presented in the Supplementary Appendix and did not significantly alter the results.

### Subgroup Analysis

Basal ganglia versus lobar 
ATACH versus ERICH

## Discussion
In this large analysis of `r sample_size` patients with intracerebral hemorrhage (ICH), we found evidence that as compared to patients with right hemispheric ICH, those with left hemispheric ICH were substantially less likely to receive aggressive care. Specifically, they had 1.79 times lower odds of receiving a neurosurgical intervention and 1.29 times lower odds of receiving an external ventricular drain. Despite receiving less aggressive care, they were more likely to have better functional outcomes at 90 days. This was robust to various definitions of functional outcomes, from the standard mRS to various HRQOL domains.

## Conclusions
