project:
  type: website

website:
  title: "ICH Laterality Analysis Notebook"
  navbar:
    left:
      - clean.qmd
      - dag.qmd
      - eda.qmd
      - aggressive_care.qmd
      - outcomes.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



