project:
  type: website

website:
  title: "ICH Laterality Analysis Notebook"
  navbar:
    left:
      - clean.qmd
      - dag.qmd
      - descriptive.qmd
      - models.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



