project:
  type: website

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "ICH Laterality Analysis Notebook"
  navbar:
    right:
      - 01-clean.qmd
      - 02-dag.qmd
      - 03-eda.qmd
      - 04-aggressive_care.qmd
      - 05-outcomes.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    code-fold: true
    code-overflow: wrap
    mainfont: 'Figtree'
    monofont: 'Source Code Pro'
    fontsize: 0.95rem