---
title: "Causal Assumptions - DAG"
code-fold: true
---


```{r setup, warning=FALSE, message=FALSE}

library(tidyverse)
library(dagitty)
library(ggdag)
library(MetBrewer)
library(here)
library(broom) # For converting model output to data frames

# set theme of all DAGs to `theme_dag()`
theme_set(theme_dag(base_family = "Cantarell"))

```

## Specify a Causal Question

Do patients with **left hemispheric** injuries have worse otucomes as compared to patients with **right hemispheric** injuries?

## Exploratory Data Analysis

```{r eda, warning=FALSE, message=FALSE}
#| fig-width: 10

data <- read_csv(here("data", "all.csv"))

data |>
  filter(ich_location == c("Lobar", "Basal Ganglia", "Thalamus")) |>
  filter(!is.na(ich_laterality)) |>
  ggplot(aes(euro_vas_90, fill = ich_laterality)) +
  geom_density(color = NA, alpha = .8)

```

## Model Our Assumptions

```{r dag, warning=FALSE, message=FALSE}
#| fig-width: 10
#| fig-height: 7

# original DAG: dagitty.net/mcLgZ8X, pw: CDKM93kbXs

node_details <- tribble(
  ~name, ~label, ~x, ~y,
  "functional_disability", "Functional Disability", 4, 1,
  "ich_laterality", "Hemispheric Laterality", 1, 1,
  "age", "Age", 2.75, 3,
  "ich_location", "ICH Location", 2, 2.75,
  "ich_volume", "ICH Volume", 1, 2.75,
  "ivh", "IVH", 1.5, 2.25,
  "gcs_baseline", "Admission GCS", 2, 3.25,
  "wlst", "Early WLST", 3.75, 2.25,
  "neurosurgery", "Neurosurgery", 2, 1.5,
)

node_labels <- node_details$label
names(node_labels) <- node_details$name

ich_dag <- dagify(
  functional_disability ~ ich_laterality + age + ich_location + ich_volume + ivh + gcs_baseline + wlst + neurosurgery,
  neurosurgery ~ ich_laterality + age + ich_location + gcs_baseline,
  wlst ~ age + ich_location + gcs_baseline + ich_volume + ivh,
  gcs_baseline ~ age + ich_location + ich_volume + ivh,
  ich_location ~ age,
  ivh ~ ich_location,
  exposure = "ich_laterality",
  outcome = "functional_disability",
  coords = node_details,
  labels = node_labels
)

ich_dag_tidy <- ich_dag |>
  tidy_dagitty() |>
  node_status()

colors <- met.brewer(name = "VanGogh1", n = 7, type = "discrete")
status_colors <- c(exposure = colors[3], outcome = colors[6], latent = "grey50")

# Fancy DAG
ggplot(ich_dag_tidy, aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_dag_edges(aes(color = "grey50")) +
  geom_dag_point(aes(color = status), size = 20) +
  geom_dag_label_repel(aes(label = label, fill = status),
    seed = 1234,
    color = "white", fontface = "bold", family = "Cantarell", size = 5
  ) +
  scale_color_manual(values = status_colors, na.value = "grey20") +
  scale_fill_manual(values = status_colors, na.value = "grey20") +
  guides(color = FALSE, fill = FALSE)

ggdag_adjustment_set(ich_dag_tidy) +
  geom_dag_edges(aes(color = "grey50")) +
  geom_dag_point(aes(color = status), size = 20) +
  geom_dag_label_repel(aes(label = label, fill = status),
    seed = 1234,
    color = "white", fontface = "bold", family = "Cantarell", size = 5
  ) +
  scale_color_manual(values = status_colors, na.value = "grey20") +
  scale_fill_manual(values = status_colors, na.value = "grey20") +
  guides(color = FALSE, fill = FALSE)

ggdag_paths(ich_dag_tidy) +
  geom_dag_edges(aes(color = "grey50")) +
  geom_dag_point(aes(color = status), size = 20) +
  geom_dag_label_repel(aes(label = label, fill = status),
    seed = 1234,
    color = "white", fontface = "bold", family = "Cantarell", size = 5
  ) +
  scale_color_manual(values = status_colors, na.value = "grey20") +
  scale_fill_manual(values = status_colors, na.value = "grey20") +
  guides(color = FALSE, fill = FALSE)

adjustment_vars <- c("neurosurgery", "age", "ich_volume", "ivh", "gcs_baseline", "ich_location", "wlst")

control_for(ich_dag_tidy, var = adjustment_vars)

ggdag_adjust(ich_dag_tidy, var = adjustment_vars) +
  geom_dag_edges(aes(color = "grey50")) +
  geom_dag_point(aes(color = status), size = 20) +
  geom_dag_label_repel(aes(label = label, fill = status),
    seed = 1234,
    color = "white", fontface = "bold", family = "Cantarell", size = 5
  ) +
  scale_color_manual(values = status_colors, na.value = "grey20") +
  scale_fill_manual(values = status_colors, na.value = "grey20") +
  guides(color = FALSE, fill = FALSE)


ggdag_dseparated(ich_dag_tidy, controlling_for = adjustment_vars) +
  geom_dag_edges(aes(color = "grey50")) +
  geom_dag_point(aes(color = status), size = 20) +
  geom_dag_label_repel(aes(label = label, fill = status),
    seed = 1234,
    color = "white", fontface = "bold", family = "Cantarell", size = 5
  ) +
  scale_color_manual(values = status_colors, na.value = "grey20") +
  scale_fill_manual(values = status_colors, na.value = "grey20") +
  guides(color = FALSE, fill = FALSE)

```


```{r}


```