---
title: "Descriptive Analysis"
---

```{r setup, warning=FALSE, message=FALSE}

library(tidyverse)
library(dagitty)
library(ggdag)
library(MetBrewer)
library(here)
library(tableone)
library(gt)
library(gtExtras)
library(broom)


data <- read_csv(here("data", "all.csv"))

# converting some columns to factors
factors <- c("sex", "race", "euro_mobility_90", "euro_mobility_180", "euro_mobility_365", "euro_selfcare_90", "euro_selfcare_180", "euro_selfcare_365", "euro_usual_90", "euro_usual_180", "euro_usual_365", "euro_pain_90", "euro_pain_180", "euro_pain_365", "euro_anxiety_90", "euro_anxiety_180", "euro_anxiety_365", "location_90", "location_180", "location_365", "ethnicity", "stroke", "cad", "chf", "afib", "pvd", "hld", "dm2", "tobacco", "htn_meds", "dm2_meds", "ich_location", "ich_laterality", "ivh", "evd", "neurosurgery_evac", "tracheostomy", "peg", "dnr_binary", "dni_binary", "comfort_care_binary", "mrs_90", "mrs_180", "mrs_365", "euroqol_90_assessment_source", "euroqol_180_assessment_source", "euroqol_365_assessment_source", "euro_mobility_365_binary", "euro_selfcare_365_binary", "euro_usual_365_binary", "euro_pain_365_binary", "euro_anxiety_365_binary", "study", "enrolling_country", "treatment_group", "euro_mobility_90_binary", "euro_selfcare_90_binary", "euro_usual_90_binary", "euro_pain_90_binary", "euro_anxiety_90_binary", "cocaine", "anticoagulated", "etoh", "mrs_270", "location_30")

data <- data |>
  mutate_at(factors, factor)

data <- data |>
  filter(ich_location == c("Lobar", "Basal Ganglia", "Thalamus")) |>
  filter(!is.na(ich_laterality))

```



```{r tableone}
#| fig-width: 20

# have to fix time from symptom onset to presentation in ED (units seems to be jacked up)

table1_vars <- c("age", "sex", "race", "ethnicity", "htn", "dm2", "tobacco", "sbp_baseline", "gcs_baseline", "nihss_baseline", "ich_volume_baseline", "ivh", "ich_location", "neurosurgery_evac", "comfort_care_binary", "study")

table1 <- CreateTableOne(vars = table1_vars, data = data, strata = "ich_laterality")

table1

```