---
title: "Ordinal Regression - Kruscke"
code-fold: true
---

```{r setup, warning=FALSE, message=FALSE}

library(tidyverse)
library(brms)
library(cmdstanr)
library(here)
library(ordinal)


# seeds
set.seed(160)
BAYES_SEED <- 160

# Bayes
options(
  mc.cores = parallel::detectCores(),
  brms.backend = "cmdstanr"
)

```


## The Case of a Single Group

In this scenario, we will use modified Rankin scores from the ERICH dataset. First we will analyze this without any predictors.

```{r import data, warning=FALSE, message=FALSE}

data <- read_rds(here("data", "all.rds"), refhook = NULL) |>
  drop_na(mrs_90)

erich <- data |>
  filter(study == "ERICH")

erich_plot <- erich |>
  count(mrs_90) |>
  mutate(
    prob = n / nrow(erich),
    cum_prob = cumsum(n / nrow(erich))
  )

fit <- brm(
  data = erich,
  family = cumulative(logit),
  mrs_90 ~ 1
)

fit

draws <- as_draws_df(fit) |>
  mutate(across(starts_with("b_"), inv_logit_scaled)) |>
  pivot_longer(starts_with("b_")) |>
  group_by(name) |>
  summarize(
    mean = mean(value),
    sd = sd(value),
    ll = quantile(value, probs = 0.025),
    up = quantile(value, probs = 0.975)
  )

```
