---
title: "Models"
code-fold: true
---

```{r setup, warning=FALSE, message=FALSE}

library(tidyverse)
library(ordinal)
library(marginaleffects)
library(modelsummary)
library(parameters)
library(brms)
library(cmdstanr)
library(tidybayes)
library(broom.mixed)
library(ggdist)
library(broom)
library(janitor)
library(gt)
library(here)

# seeds
set.seed(160)
BAYES_SEED <- 160

# Bayes
options(
  mc.cores = parallel::detectCores(),
  brms.backend = "cmdstanr"
)

data <- read_rds(here("data", "all.rds"), refhook = NULL)

data <- data |>
  filter(ich_location == "Basal Ganglia" | ich_location == "Thalamus" | ich_location == "Lobar") |>
  select(study, age, ich_laterality, ich_location, ich_volume_baseline, gcs_baseline, ivh, neurosurgery_evac, sbp_baseline, mrs_90_01, mrs_90_02, mrs_90_03, mrs_90_04, mrs_90) |>
  drop_na(ich_laterality)

data$ich_location <- fct_drop(data$ich_location)
data$ich_laterality <- fct_drop(data$ich_laterality)

data_erich_atach <- data |>
  filter(study == "ERICH" | study == "ATACH2")


# plot stuff
theme_set(theme_minimal(base_family = "Cantarell"))

```

## Dichotimized mRS: 0-3 vs. 4-6

### Priors

Based on previous knowledge, we can say that on average, there is a 60% chance of a good outcome of mRS 0-3. On the log-odds scale, that would be `qlogis(0.6) = 0.41`. That can range a lot from 20% to 80%, so in log-odds we can say that is `qlogis(0.2) = -1.38` as the variance.

```{r priors log_odds}


```

```{r eda}

model_mrs03 <- brm(
  mrs_90_03 ~ ich_laterality + age + ich_location + ich_volume_baseline + gcs_baseline + neurosurgery_evac,
  family = bernoulli(link = "logit"),
  data = data
)

print(model_mrs03)

pp_check(model_mrs03, ndraws = 500)

model_parameters(model_mrs03,
  centrality = "mean", dispersion = TRUE,
  test = FALSE, verbose = FALSE, ci_method = "hdi", priors = TRUE,
  exponentiate = TRUE
) |>
  print(digits = 3, zap_small = TRUE)

model_mrs_90 <- brm(
  mrs_90 ~ ich_laterality + age + ich_location + ich_volume_baseline + gcs_baseline + neurosurgery_evac,
  family = cumulative(link = "logit"),
  data = data_erich_atach
)

pp_check(model_mrs_90, type = "ecdf_overlay", ndraws = 500)

model_parameters(model_mrs_90,
  centrality = "mean", dispersion = TRUE,
  test = FALSE, verbose = FALSE, ci_method = "hdi", priors = TRUE,
  exponentiate = TRUE
) |>
  print(digits = 3, zap_small = TRUE)

model_mrs_90_all <- brm(
  mrs_90 ~ ich_laterality + age + ich_location + ich_volume_baseline + gcs_baseline + neurosurgery_evac,
  family = cumulative(link = "logit"),
  data = data
)

pp_check(model_mrs_90_all, type = "ecdf_overlay", ndraws = 500)

model_parameters(model_mrs_90_all,
  centrality = "mean", dispersion = TRUE,
  test = FALSE, verbose = FALSE, ci_method = "hdi", priors = TRUE,
  exponentiate = TRUE
) |>
  print(digits = 3, zap_small = TRUE)

```

